[package]
name = "packet-capture"
version = "0.1.0"
authors = ["hiroki-personal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pnet = "0.26.0"
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.1"